name: 'deploy-snapshot'
on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.7.0
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Configure Maven
      env:
        M2_SETTINGS_XML: ${{ secrets.M2_SETTINGS_XML }}
      run: |
        set -euo pipefail
        mkdir -p $HOME/.m2
        echo "$M2_SETTINGS_XML" > $HOME/.m2/settings.xml

    - name: Build & Deploy
      run: 'mvn clean deploy'
