name: 'test-pull-requests'
on:
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.8.0
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build & Package
      run: 'mvn clean package'
